created new portfolio page with enhanced ui
0silverback0/LandingPages pull request #62
Opened 2023-10-24 04:15 UTC by Ro-shni

2023-10-24 04:33 UTC, Ro-shni commented
kindly suggest changes if required!

2023-10-24 10:41 UTC, 0silverback0 commented on portfolio new/index.html
> +
add a link here in your home tab to /index.html for ease of navigation back to repo landing page

2023-10-24 10:43 UTC, 0silverback0 requested changes

2023-10-24 10:43 UTC, 0silverback0 commented on portfolio new/index.html
also in the projects root directory add your information to the index.html file so that your project can be merged

2023-10-24 12:03 UTC, Ro-shni commented
I've made the requested changes could you verify it and update me?

2023-10-24 12:51 UTC, 0silverback0 commented
![image](https://github.com/0silverback0/LandingPages/assets/38266625/495ffe0a-72b7-49f8-859f-59010978af8b)

Add your info in the root index.html so your project can be viewed

2023-10-24 13:50 UTC, Ro-shni commented
![image](https://github.com/0silverback0/LandingPages/assets/112896479/3adcef36-423e-4038-b929-f26b50506e73)


I've updated it. could you please recheck?

2023-10-24 14:03 UTC, Ro-shni commented
![image](https://github.com/0silverback0/LandingPages/assets/112896479/9fe814df-fa01-4474-98a9-f444fc980b70)

portfolio new  pr#62 issue #61

2023-10-25 01:46 UTC, 0silverback0 commented
please just pull the latest changes and commit then

2023-10-25 01:57 UTC, Ro-shni commented
@0silverback0 , yes I have committed the latest pull. could u verify and add Hactoberfest accepted label to this pr?

2023-10-25 01:58 UTC, merged