add responsive landing page #63 ,./
0silverback0/LandingPages pull request #64
Opened 2023-10-24 04:55 UTC by KRRISHSINGH08

@0silverback0, Please merge this PR under the issue #63

2023-10-24 10:48 UTC, 0silverback0 requested changes

2023-10-24 10:48 UTC, 0silverback0 commented on Responsive Ecommerce Landing Page/index.html
> +                <a href="#Home">Home</a>
this should link to the repo landing page /index.html then add your information in the repos index.html so your project and github can be view from the repo landing page

2023-10-24 13:46 UTC, KRRISHSINGH08 commented
Please have a look @0silverback0

2023-10-25 01:33 UTC, 0silverback0 commented on Responsive Ecommerce Landing Page/index.html
> +                <a href="#Home">Home</a>
line 21 should be <a href="/index.html">Home</a> for ease of navigation

2023-10-25 01:36 UTC, 0silverback0 commented on Responsive Ecommerce Landing Page/index.html
> +                <a href="#Home">Home</a>
also in the root directory add your information so that your site is visible on the home page

2023-10-25 03:08 UTC, KRRISHSINGH08 commented
@0silverback0 I have added link to index.html in line 21 and also my info in the footer section. I think this will do

2023-10-25 03:16 UTC, merged

2023-10-25 03:17 UTC, 0silverback0 commented
merged!