New Landing Page
0silverback0/LandingPages pull request #73
Opened 2023-10-24 11:50 UTC by harshit1142

Added a Responsive Movie Landing Page

Please add hacktoberfest label

2023-10-24 12:47 UTC, 0silverback0 requested changes

2023-10-24 12:47 UTC, 0silverback0 commented on MovieLanding Page/index.html
> +                    <a href="#highlight " id="navi" class="link">Home</a>
Should link to /index.html also

2023-10-24 13:04 UTC, harshit1142 commented on MovieLanding Page/index.html
> +                    <a href="#highlight " id="navi" class="link">Home</a>
Okay wait.

2023-10-24 13:20 UTC, harshit1142 commented
Done

2023-10-25 01:29 UTC, 0silverback0 commented
please pull the lates changes and commit

2023-10-25 04:10 UTC, closed without merging

2023-10-25 04:13 UTC, harshit1142 commented
Please Add Hacktoberfest label if possilble.